# Generated by Django 2.0 on 2018-04-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuoxiao', '0002_auto_20180425_1725'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Account',
        ),
    ]
