# Generated by Django 2.0 on 2018-04-25 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nuoxiao', '0003_auto_20180425_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('subtitle', models.CharField(max_length=50)),
                ('introduction', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('imgurl', models.CharField(max_length=500)),
                ('dateTime', models.DateTimeField()),
                ('links', models.IntegerField()),
                ('reads', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('introduce', models.CharField(max_length=140)),
                ('cover_url', models.CharField(max_length=500, null=True)),
                ('description', models.TextField()),
                ('dateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50, null=True)),
                ('subject', models.CharField(max_length=50, null=True)),
                ('introduce', models.CharField(max_length=140, null=True)),
                ('icon', models.CharField(max_length=50, null=True)),
                ('dateTime', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AddField(
            model_name='garden',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuoxiao.Users'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuoxiao.Users'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuoxiao.Garden'),
        ),
    ]
