# Generated by Django 2.0 on 2018-04-26 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nuoxiao', '0004_auto_20180425_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentId', models.IntegerField()),
                ('title', models.CharField(max_length=50, null=True)),
                ('contnet', models.CharField(max_length=500)),
                ('references', models.IntegerField()),
                ('replys', models.IntegerField()),
                ('dateTime', models.DateTimeField()),
                ('links', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuoxiao.Users')),
                ('blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuoxiao.Blogs')),
            ],
        ),
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentId', models.IntegerField()),
                ('content', models.CharField(max_length=500, null=True)),
                ('references', models.IntegerField()),
                ('links', models.IntegerField()),
                ('dateTime', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuoxiao.Users')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.IntegerField()),
                ('dateTime', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuoxiao.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themeName', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('introduce', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('members', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuoxiao.Users')),
            ],
        ),
        migrations.CreateModel(
            name='ThemeBlogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('subtitle', models.CharField(max_length=50)),
                ('introduction', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('imgurl', models.CharField(max_length=500)),
                ('dateTime', models.DateTimeField()),
                ('links', models.IntegerField()),
                ('reads', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuoxiao.Users')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuoxiao.Theme')),
            ],
        ),
        migrations.AddField(
            model_name='discusstopic',
            name='themeBlog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nuoxiao.ThemeBlogs'),
        ),
        migrations.AddField(
            model_name='discuss',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuoxiao.DiscussTopic'),
        ),
    ]
