# Generated by Django 2.0 on 2018-04-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuoxiao', '0005_auto_20180426_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='introduction',
            field=models.CharField(max_length=400),
        ),
    ]
