"""
Django settings for restapi project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

ENVIRONMENT = os.getenv('ENVIRONMENT', 'development')
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7sir)emxey_4=9$sb@itz)t9ii6**^p1xvf)i(4*!ba+4e^#n+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',

    'coreapi',
    'schema',
    'markupsafe',
    # DRF配置
    'rest_framework',
    # 精确搜索
    'django_filters',
    # 权限认证，Token配置
    'rest_framework.authtoken',
    # 跨域访问
    'corsheaders',
    'nuoxiao.apps.NuoxiaoConfig',
]


'''
    我们也需要一些全局设置。我们想要分页（pagination），我们希望API只对管理用户开发。
    DEFAULT_FILTER_BACKENDS: 全局的 filter
    rest_framework.permissions.AllowAny: 设置全局默认权限
'''
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework.authentication.BasicAuthentication',
                                       'rest_framework.authentication.SessionAuthentication',
                                       'rest_framework.authentication.TokenAuthentication', ),  #权限认证
    # 其中写认证的类的路径，不要在views中，这里我放在了settings目录下authentication.py中
    # 'DEFAULT_AUTHENTICATION_CLASSES': ('nuoxiao.settings.authentication.Authentication',),
    # "UNAUTHENTICATED_USER": lambda: "nuoxiao",  # 匿名用户配置，只需要函数或类的对应的返回值，对应request.user="匿名"
    # "UNAUTHENTICATED_token": None,  # 匿名token，只需要函数或类的对应的返回值，对应request.auth=None
    # 全局认证 postman 接口测试去掉验证， 'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAdminUser', 'rest_framework.permissions.AllowAny',),
    # 搜索 pip install django-filter
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),
    # # 全局配置，自定义频率控制
    # "DEFAULT_THROTTLE_CLASSES": ('nuoxiao.settings.throttle.VisitThrottle',),
    # "DEFAULT_THROTTLE_RATES": {'WD': '5/m'},  # 速率配置每分钟不能超过5次访问，WD是scope定义的值，
    # 版本配置
    # "DEFAULT_VERSIONING_CLASS": "nuoxiao.settings.version.URLPathVersioning",  # 类的路径
    # "DEFAULT_VERSION": 'v1',  # 默认的版本
    # "ALLOWED_VERSIONS": ['v1', 'v2'],  # 允许的版本,这里只允许V1和v2
    # "VERSION_PARAM": 'version',  # get方式url中参数的名字 如?version=v1
    # # 默认内容协商类
    # 'DEFAULT_CONTENT_NEGOTIATION_CLASS': 'nuoxiao.settings.negotiation.IgnoreClientContentNegotiation',
    # 分页 1,  #  'int' object is not callable' 添加会报错
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'DEFAULT_PAGINATION_CLASS': 'nuoxiao.settings.pagination.DefaultSetPagination',   # 重写分页
    'PAGE_SIZE': 10
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',    # 跨域访问，安装django-cors-headers  API通常都是由不同域名来进行调用，放在CsrfViewMiddleware之前
    'django.middleware.csrf.CsrfViewMiddleware',      # from data 验证
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'restapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates"),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'debug': DEBUG,
        },
    },
]

WSGI_APPLICATION = 'restapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # },
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'nuoxiao_restapi',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

#设置时区

# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'UTC'
LANGUAGE_CODE = 'zh-hans'  #中文支持，django1.8以后支持；1.8以前是zh-cn
TIME_ZONE = 'Asia/Shanghai'  # 'Asia/shanghai'
USE_I18N = True
USE_L10N = True
USE_TZ = False   #默认是Ture，时间是utc时间，由于我们要用本地时间，所用手动修改为false

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'


if ENVIRONMENT == 'production':
    DEBUG = False
    SECRET_KEY = os.getenv('SECRET_KEY')
    SESSION_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_REDIRECT_EXEMPT = []
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
